#!/usr/bin/env bash
set -euo pipefail

page_title="${1:-BCA Test Reports}"
page_description="${2:-Reports generated by GitHub Actions.}"

site_dir="${REPORT_SITE_DIR:-reports/site}"
playwright_report_dir="${PLAYWRIGHT_REPORT_DIR:-reports/playwright-html}"
allure_report_dir="${ALLURE_REPORT_DIR:-reports/allure-report}"

rm -rf "$site_dir"
mkdir -p "$site_dir/playwright" "$site_dir/allure"

if [ -d "$playwright_report_dir" ]; then
  cp -R "$playwright_report_dir"/. "$site_dir/playwright/"
else
  cat > "$site_dir/playwright/index.html" <<'HTML'
<!doctype html>
<html lang="en"><body><h1>Playwright report was not generated</h1></body></html>
HTML
fi

if [ -d "$allure_report_dir" ]; then
  cp -R "$allure_report_dir"/. "$site_dir/allure/"
else
  cat > "$site_dir/allure/index.html" <<'HTML'
<!doctype html>
<html lang="en"><body><h1>Allure report was not generated</h1></body></html>
HTML
fi

cat > "$site_dir/index.html" <<HTML
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${page_title}</title>
    <style>
      body { margin: 0; font-family: Arial, sans-serif; background: #0f172a; color: #e5e7eb; }
      main { max-width: 900px; margin: 0 auto; padding: 56px 24px; }
      h1 { margin: 0 0 12px; font-size: 36px; }
      p { color: #cbd5e1; line-height: 1.6; }
      .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; margin-top: 28px; }
      a { display: block; padding: 22px; border: 1px solid #334155; border-radius: 8px; color: #f8fafc; text-decoration: none; background: #111827; }
      a:hover { border-color: #38bdf8; }
      strong { display: block; margin-bottom: 8px; font-size: 20px; }
      span { color: #94a3b8; }
    </style>
  </head>
  <body>
    <main>
      <h1>${page_title}</h1>
      <p>${page_description}</p>
      <div class="grid">
        <a href="./playwright/"><strong>Playwright HTML Report</strong><span>Best for traces, screenshots, videos, and debugging failed tests.</span></a>
        <a href="./allure/"><strong>Allure Report</strong><span>Polished report view with suites, history-style navigation, and test details.</span></a>
      </div>
    </main>
  </body>
</html>
HTML
